synonym_map={

    # 🩺 Gastrointestinal
    "barfing": "vomiting",
    "throwing up": "vomiting",
    "vomits": "vomiting",
    "nausea": "vomiting",
    "dog keeps vomiting": "vomiting",
    "throws up": "vomiting",
    "upset stomach": "diarrhea",
    "loose stool": "diarrhea",
    "bloody stool": "bloodystool",
    "bloody diarrhea": "bloodystool",
    "pooping blood": "bloodystool",
    "blood in stool": "bloodystool",
    "blood in pee": "bloodinurine",
    "passing gas": "Passing gases",

    # 🫁 Respiratory & Circulatory
    "sneezes": "sneezing",
    "keeps sneezing": "sneezing",
    "frequent sneezing": "sneezing",
    "nose is runny": "nasaldischarge",
    "runny nose": "nasaldischarge",
    "labored breathing": "difficultyinbreathing",
    "breathing trouble": "difficultyinbreathing",
    "shortness of breath": "difficultyinbreathing",
    "breathing seems labored": "difficultyinbreathing",
    "breathing is hard": "difficultyinbreathing",
    "heavy breathing": "difficultyinbreathing",
    "hard to breathe": "difficultyinbreathing",
    "reverse sniffing": "reversesneezing",
    "gag": "gagging",
    "gagging": "gagging",
    "rapid heartbeat": "rapidheartbeat",
    "cyanosis": "palegums",
    "bluish gums": "palegums",
    "gums look blue": "palegums",
    "gums appear blue": "palegums",

    # 🧠 Neurological / Behavioral / Cognitive
    "fits": "seizures",
    "convulsions": "seizures",
    "twitching randomly": "seizures",
    "keeps twitching": "seizures",
    "flinches randomly": "seizures",
    "walks in circles": "Neurological Disorders",
    "pacing in circles": "Neurological Disorders",
    "compulsive pacing": "Neurological Disorders",
    "stares into space": "Neurological Disorders",
    "doesn't respond when called": "Neurological Disorders",
    "seems confused": "Neurological Disorders",
    "forgets commands": "Neurological Disorders",
    "gets stuck in corners": "Neurological Disorders",
    "wanders aimlessly": "Neurological Disorders",
    "barks at nothing": "Neurological Disorders",
    "lost at home": "Neurological Disorders",
    "confused at night": "Neurological Disorders",
    "trembles when touched": "highlyexcitable",
    "freaks out when touched": "highlyexcitable",
    "acts anxious": "highlyexcitable",
    "collapsed": "fainting",
    "dizzy": "fainting",
    "collapsing": "fainting",
    "pass out": "fainting",
    "unconscious": "fainting",
    "coma": "fainting",
    "angry behavior": "aggression",
    "bitey": "aggression",
    "aggressive": "aggression",
    "snaps at invisible things": "irritable",
    "growls at shadows": "irritable",
    "irritated": "irritable",
    "hides in corners": "depression",
    "looks confused": "lethargy",
    "seems dazed": "lethargy",
    "dazed": "depression",
    "unfocused": "depression",
    "non responsive": "depression",
    "sad": "depression",
    "not responsive": "depression",

    # 🧴 Dermatological / Skin / Fur
    "itching skin": "skinsores",
    "itchy": "skinsores",
    "dry skin": "skinsores",
    "rash": "skinsores",
    "scabs": "skinsores",
    "patchy fur": "skinsores",
    "fur loss": "skinsores",
    "loss of fur": "skinsores",
    "hair missing": "skinsores",
    "bald patches": "skinsores",
    "skin redness": "skinsores",
    "face rubbing": "skinsores",
    "licking skin": "skinsores",
    "scratching": "skinsores",
    "smelly fur": "smelly",

    # 🩸 Urinary & Renal
    "pee problem": "decreasedurination",
    "hard to urinate": "decreasedurination",
    "frequent urination": "increasedurination",
    "pees constantly": "increasedurination",
    "always peeing": "increasedurination",
    "frequent peeing": "increasedurination",
    "peeing often": "increasedurination",
    "drinks a lot": "increasedthirst",
    "always thirsty": "increasedthirst",
    "drinking excessively": "increasedthirst",
    "drinks constantly": "increasedthirst",
    "not drinking": "decreasedthirst",
    "refuses water": "hydrophobia",
    "avoids water": "hydrophobia",
    "won't go near water": "hydrophobia",
    "doesn't want water": "hydrophobia",
    "fear of liquids": "hydrophobia",
    "fear of water": "hydrophobia",
    "sweet smelling breath": "badbreath",
    "odd smelling breath": "badbreath",
    "breath smells sweet": "badbreath",

    # 🧠 Cognition / Aging / Conceptual
    "cognitiveimpairment": "Neurological Disorders",
    "disorientation": "Neurological Disorders",
    "memoryloss": "Neurological Disorders",
    "balanceissues": "Neurological Disorders",
    "blurredvision": "Losing sight",
    "seems lost": "Neurological Disorders",

    # 👄 Oral / Mouth / Saliva
    "drooling": "excesssalivation",
    "slobbering": "excesssalivation",
    "saliva": "excesssalivation",
    "foamy saliva": "foamingatmouth",
    "foam around mouth": "foamingatmouth",
    "foaming mouth": "foamingatmouth",
    "foam around its mouth": "foamingatmouth",
    "frothing": "foamingatmouth",
    "bad breath": "badbreath",
    "bad smell mouth": "badbreath",
    "foul smelling breath": "badbreath",
    "smelly breath": "badbreath",
    "sweet breath": "badbreath",
    "breath smells weird": "badbreath",
    "weird smelling breath": "badbreath",
    "red gums": "inflammation_mouth",
    "gum bleeding": "inflammation_mouth",
    "pale gum": "palegums",
    "pale gums": "palegums",
    "yellow gums": "jaundice",
    "mouth ulcers": "ulcersinmouth",
    "ulcers in mouth": "ulcersinmouth",

    # 🧍 General Physical State
    "very tired": "fatigue",
    "extremely tired": "fatigue",
    "low energy": "fatigue",
    "acting sluggish": "fatigue",
    "sluggish": "fatigue",
    "tired quickly": "fatigue",
    "gets tired easily": "fatigue",
    "weak": "weakness",
    "weak legs": "weakness",
    "can't walk properly": "lameness",
    "limping": "lameness",
    "can't walk": "paralysis",
    "drags legs": "paralysis",
    "lazy": "laziness",
    "lethargic": "lethargy",
    "doesn't play": "lethargy",
    "not active": "lethargy",
    "weight loss": "weightloss",
    "visibly thinner": "weightloss",
    "lost weight": "weightloss",
    "skinny": "weightloss",
    "keeps losing weight": "weightloss",
    "losing weight": "weightloss",
    "weight keeps dropping": "weightloss",
    "pain": "pain",
    "discomfort": "pain",
    "soft whining": "pain",
    "whines when lying down": "pain",
    "whining softly": "pain",
    "stiff muscles": "stiffness",
    "moves awkwardly": "stiffness",
    "walks stiffly": "stiffness",
    "stiff when walking": "stiffness",
    "seems stiff": "stiffness",
    "walking oddly": "stiffness",
    "hot body": "fever",
    "hot body": "fever",
    "has a fever": "fever",
    "high temperature": "fever",
    "loss of appetite": "reducedappetite",
    "not hungry": "reducedappetite",
    "no appetite": "reducedappetite",
    "ignores food": "reducedappetite",
    "won't eat": "reducedappetite",
    "refuses to eat": "reducedappetite",
    "not eating": "reducedappetite",
    "not eating at all": "reducedappetite",
    "looks weak": "weakness",
    "feeling weak": "weakness",
    #####
    "not eating at all": "reducedappetite",
    "looks weak": "weakness",
    "feeling weak": "weakness",
    "severe diarrhea": "diarrhea",
    "runny stool": "diarrhea",
    "vomiting constantly": "vomiting",
    "won't move": "lethargy",
    "throws up": "vomiting",
    "very tired": "fatigue",
    "has bloody pee": "bloodinurine",
    "breath smells bad": "halitosis",
    "shaking or twitching": "seizures",
    "not playful": "lethargy",
    
    "very weak": "weakness",
    "doesn't want to move": "lethargy",
    "getting worse": "acuteprogression",
    "refuses to stand": "lethargy",
    "looks exhausted": "fatigue",
  "acting hyper": "highlyexcitable",
  "snapping without warning": "aggression",
  "scared for no reason": "anxiety",
  "stares at walls": "disorientation" , 
  "makes a honking sound": "reversesneezing",
  "coughs at night": "coughing",
  "breathing sounds harsh": "difficultyinbreathing"

}
synonym_map .update( {
    # Gastrointestinal
    "vomiting yellow foam": "vomiting",
    "refusing to eat": "reducedappetite",
    "won’t touch food": "reducedappetite",
    "diarrhea all day": "diarrhea",
    "vomiting constantly": "vomiting",
    "dog has purged everything": "Purging",
    "bloody stool": "bloodystool",
    "gassy and bloated": "Passing gases",

    # Neurological & Behavioral
    "foaming at mouth": "foamingatmouth",
    "twitching and shaking": "seizures",
    "acting hyper": "highlyexcitable",
    "growling and snapping": "aggression",
    "pacing around anxiously": "irritable",
    "doesn’t respond to name": "Neurological Disorders",

    # Respiratory
    "coughing at night": "coughing",
    "honking like choking": "reversesneezing",
    "struggling to breathe": "difficultyinbreathing",
    "sneezing often": "sneezing",
    "nose is runny": "nasaldischarge",

    # Abdominal
    "tight belly": "swollenbelly",
    "pain when touched": "Tender abdomen",
    "dog keeps gagging": "gagging",
    "licking floor repeatedly": "pica",

    # Systemic / Appearance
    "extremely tired": "fatigue",
    "really weak": "weakness",
    "gums look pale": "palegums",
    "rapid heartbeat": "rapidheartbeat",
    "weight dropping fast": "weightloss",
    "feels feverish": "fever",
    "breath smells bad": "badbreath",
    "skin is flaky": "Dandruff",
    "eyes look inflamed": "inflammation_eyes",
    "mouth looks swollen": "inflammation_mouth"
})