# Generated by Django 5.2.4 on 2025-07-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Syria', max_length=100),
        ),
    ]
