# Generated by Django 5.1.7 on 2025-03-13 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feline_panleukopenia_virus', models.BooleanField(default=False)),
                ('feline_herpes_virus', models.BooleanField(default=False)),
                ('feline_calicivirus', models.BooleanField(default=False)),
                ('chlamydophila_felis', models.BooleanField(default=False)),
                ('feline_leukemia_virus', models.BooleanField(default=False)),
                ('feline_immunodeficiency_virus', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pet')),
            ],
        ),
        migrations.CreateModel(
            name='DogVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canine_adenovirus_2', models.BooleanField(default=False)),
                ('canine_distemper_virus', models.BooleanField(default=False)),
                ('canine_parainfluenza_virus', models.BooleanField(default=False)),
                ('canine_parvovirus', models.BooleanField(default=False)),
                ('leptospira_species', models.BooleanField(default=False)),
                ('rabies_virus', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pet')),
            ],
        ),
    ]
