# Generated by Django 5.1.7 on 2025-03-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_adoptionpost_breedingpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('toys', 'toys'), ('food', 'food'), ('clothes', 'clothes')], max_length=7)),
                ('details', models.TextField(max_length=100)),
                ('shipping', models.BooleanField()),
            ],
        ),
    ]
