# Generated by Django 4.2.5 on 2025-07-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
    ]
