# Generated by Django 4.2.5 on 2025-07-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('syria', 'Syria'), ('palestine', 'Palestine'), ('iraq', 'Iraq'), ('jordan', 'Jordan'), ('lebanon', 'Lebanon'), ('egypt', 'Egypt'), ('saudi_arabia', 'Saudi Arabia'), ('turkey', 'Turkey'), ('iran', 'Iran'), ('yemen', 'Yemen'), ('kuwait', 'Kuwait'), ('uae', 'United Arab Emirates'), ('qatar', 'Qatar'), ('oman', 'Oman'), ('libya', 'Libya'), ('tunisia', 'Tunisia'), ('algeria', 'Algeria'), ('morocco', 'Morocco'), ('sudan', 'Sudan'), ('bahrain', 'Bahrain')], default='syria', max_length=100),
        ),
    ]
