# Generated by Django 4.2.5 on 2025-03-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_adoptionpost_photo_breedingpost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
    ]
