# Generated by Django 5.2.4 on 2025-07-23 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_pendinguser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 23, 15, 15, 12, 348641, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breedingpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 23, 15, 15, 17, 192211, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
