# Generated by Django 4.2.5 on 2025-08-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_adoptionpost_created_at_breedingpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='details',
            field=models.CharField(default='', max_length=700),
        ),
    ]
