# Generated by Django 4.2.5 on 2025-05-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_store_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
